In [1]:
import tensorflow as tf
print(tf.__version__)

import numpy as np

1.3.0


## `tf.argmax`
return the index with the largest value across axes of a tensor.

`axis=0`, comparison in columns, output a row vector

`axis=1`, comparison in row,    output a column vector

In [16]:
logits = tf.constant([[31., 23., 1.],[18.,  3., 25.]], name='logits')
predict = tf.nn.softmax(logits)
arg = tf.argmax(predict, axis=0) 

with tf.Session() as sess:
    print(sess.run(predict))
    print(sess.run(arg))

[[  9.99664664e-01   3.35350138e-04   9.35448482e-14]
 [  9.11051233e-04   2.78692680e-10   9.99089003e-01]]
[0 0 1]


## `tf.equal`
return the truth value of (x==y) element-wise

如果在实际中常常也将False作为0、True作为1来处理，
则需要使用`tf.cast`进行强制类型转换。
因此能够求和或平均值。

In [23]:
a = tf.constant([[1, 2, 3]])
b = tf.constant([[0, 2, 3]])
with tf.Session() as sess:
    print(sess.run(tf.equal(a, b)))

[[False  True  True]]


## `tf.reduce_sum`

In [28]:
with tf.Session() as sess:
    print(sess.run(tf.reduce_sum([1.,2.,3.,4.])) )
    print(sess.run(tf.reduce_mean([1.,2.,3.,4.])) )

10.0
2.5


## 体会
说实话，现在仅仅会套用一些现有的程序，进行仿照着去写；

但是没关系，千万别气馁。

遇到不懂的函数，尽量先去读官方的API文档——这里面会有很多开发文档约定成俗的表达方式，尽早熟悉；

看不懂也没关系，那就运行程序慢慢trail and error；然后再反过来API文档中表达与理解；

尽早熟悉通过阅读API文档明白许多基础的、重要的、关键的功能。