In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import numpy as np
import tensorflow as tf


a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
	writer = tf.summary.FileWriter('tmp/02', sess.graph) 
	print(sess.run(x))
writer.close() # close the writer when you’re done using it


a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.multiply(a, b, name='dot_product')
with tf.Session() as sess:
	print(sess.run(x))
# >> [[0 2]
#	 [4 6]]

5
[[0 2]
 [4 6]]


In [7]:
# tf.zeros(shape, dtype=tf.float32, name=None)
#creates a tensor of shape and all elements will be zeros (when ran in session)

x = tf.zeros([2, 3], tf.int32) 
y = tf.zeros_like(x, optimize=True)
print(tf.Session().run(y))
# print(tf.get_default_graph().as_graph_def())
with tf.Session() as sess:
    y = sess.run(y)
    print(y)

[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]


In [9]:
with tf.Session() as sess:
	print(sess.run(tf.linspace(10.0, 13.0, 8)))
	print(sess.run(tf.range(5)))
	for i in np.arange(5):
		print(i)

[ 10.          10.4285717   10.85714245  11.28571415  11.71428585
  12.1428566   12.5714283   13.        ]
[0 1 2 3 4]
0
1
2
3
4


In [10]:
samples = tf.multinomial(tf.constant([[1., 3., 1]]), 5)

with tf.Session() as sess:
	for _ in range(10):
		print(sess.run(samples))

[[1 0 1 1 1]]
[[1 1 1 1 1]]
[[1 1 0 1 1]]
[[1 1 1 1 0]]
[[1 1 1 1 1]]
[[1 1 2 1 1]]
[[1 0 2 0 1]]
[[1 0 1 1 1]]
[[1 1 1 0 1]]
[[1 1 1 1 2]]


In [11]:
t_0 = 19 
x = tf.zeros_like(t_0) # ==> 0
y = tf.ones_like(t_0) # ==> 1

with tf.Session() as sess:
	print(sess.run([x, y]))

[0, 1]


In [13]:
t_1 = ['apple', 'peach', 'banana']
x = tf.zeros_like(t_1) # ==> ['' '' '']
try:
    y = tf.ones_like(t_1) # ==> TypeError: Expected string, got 1 of type 'int' instead.
except:
    print('error')

t_2 = [[True, False, False],
       [False, False, True],
       [False, True, False]] 
x = tf.zeros_like(t_2) # ==> 2x2 tensor, all elements are False
y = tf.ones_like(t_2) # ==> 2x2 tensor, all elements are True
with tf.Session() as sess:
	print(sess.run([x, y]))

error
[array([[False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool), array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)]


In [17]:
with tf.variable_scope('meh') as scope:
	a = tf.get_variable('aa', [10])
	b = tf.get_variable('bb', [100])

writer = tf.summary.FileWriter('tmp/test', tf.get_default_graph())


x = tf.Variable(2.0)
y = 2.0 * (x ** 3)
z = 3.0 + y ** 2
grad_z = tf.gradients(z, [x, y])
with tf.Session() as sess:
	sess.run(x.initializer)
	print(sess.run(grad_z))

[768.0, 32.0]
